openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
paths:
  /users/getAllUsers:
    get:
      responses:
        '200':
          description: List of all users
  /users/getUserById/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Information of the user with the specified ID
  /users/deleteUserById/{id}:
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully

    # ... Omitted for brevity

    - uses: schemathesis/action@v1
      with:
        schema: 'https://example.schemathesis.io/openapi.json'
        token: ${{ secrets.SCHEMATHESIS_TOKEN }}

    # ... Omitted for brevity
